---
name: Create daily S3 snapshots

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '30 12 * * *'

  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: run create-daily-snapshot cli job in chosen space
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space || 'prod' }}
          cf_command: |
            run-task site-scanner-consumer
            -c "node dist/apps/cli/main.js create-daily-snapshot"
            -k 4G -m 4G
            --name github-action-create-daily-snapshots-${{ github.run_id }}
